CREATE VIEW BOLETOS_MEU_PORTAL_ROMMANEL AS 
SELECT RTRIM(E1_NUM) AS NUMERO, RTRIM(E1_TIPO) AS TIPO,RTRIM(E1_PREFIXO) AS SERIE,E1_VALOR AS VALOR,E1_SALDO AS SALDO, RTRIM(E1_CODBAR) CODBARRAS,RTRIM(E1_CODDIG) AS LINDIG,RTRIM(E1_NUMBCO) AS NUMBCO,RTRIM(E1_NUMBOR) AS BORDERO,
CAST(E1_EMISSAO AS DATE) AS EMISSAO, CAST(E1_BAIXA AS DATE) AS PAGAMENTO
,A1.R_E_C_N_O_ AS RECA1,E1.R_E_C_N_O_ AS RECE1
FROM SE1010 E1 INNER JOIN SA1010 A1 ON A1_COD = E1_CLIENTE AND A1_LOJA = E1_LOJA
AND E1.D_E_L_E_T_ = '' AND A1.D_E_L_E_T_ = ''
WHERE E1_TIPO IN ('BO ','BOL')