CREATE VIEW RECEBER_MEU_PORTAL_ROMMANEL AS 
SELECT E1_FILIAL AS EMPRESA,RTRIM(M0_FILIAL) AS NOMEEMP,RTRIM(E1_NUM) AS NUMERO,RTRIM(E1_PARCELA) AS PARCELA, RTRIM(E1_TIPO) AS TIPO,RTRIM(E1_PREFIXO) AS SERIE,E1_VALOR AS VALOR,E1_SALDO AS SALDO, RTRIM(E1_CODBAR) CODBARRAS,RTRIM(E1_CODDIG) AS LINDIG,RTRIM(E1_NUMBCO) AS NUMBCO,RTRIM(E1_NUMBOR) AS BORDERO,
CAST(E1_EMISSAO AS DATE) AS EMISSAO,CAST(E1_VENCREA AS DATE) AS VENCREA, CAST(E1_VENCTO AS DATE) AS VENCTO, CAST(E1_BAIXA AS DATE) AS PAGAMENTO
,A1.R_E_C_N_O_ AS RECA1,E1.R_E_C_N_O_ AS RECE1,
ISNULL((SELECT RTRIM(D2_COD) FROM SD2010 (NOLOCK) D2 WHERE D2_DOC = E1_NUM AND D2_SERIE = E1_PREFIXO AND D2.D2_FILIAL = E1_FILIAL AND D2.D_E_L_E_T_ = '' AND D2_ITEM = '01'  ),'') AS PRODUTO,
ISNULL((SELECT SUM(D2_QUANT) FROM SD2010 (NOLOCK) D2 WHERE D2_DOC = E1_NUM AND D2_SERIE = E1_PREFIXO AND D2.D2_FILIAL = E1_FILIAL AND D2.D_E_L_E_T_ = ''  ),'') AS QUANTIDADE,
CASE WHEN E1_SALDO <= 0 THEN 'Pago' WHEN E1_SALDO > 0 AND E1_BAIXA <> '' THEN 'Pago Parcialmente' ELSE 'Pendente' END AS SITUACAO,
CASE E1_TIPO WHEN 'BOL'  THEN 'Boleto' WHEN 'FT' THEN 'Faturado' WHEN 'NP' THEN 'Nota Promissória' WHEN 'REN' THEN 'Renegociação' ELSE 'Negociado' END AS TIPODESC
FROM SE1010 (NOLOCK) E1 INNER JOIN SA1010 (NOLOCK) A1 ON A1_COD = E1_CLIENTE AND A1_LOJA = E1_LOJA AND E1.D_E_L_E_T_ = '' AND A1.D_E_L_E_T_ = ''
INNER JOIN SYS_COMPANY (NOLOCK) SM0 ON SM0.M0_CODFIL = E1_FILIAL AND SM0.D_E_L_E_T_ = '' AND M0_CODIGO = '01'
WHERE E1_TIPO IN ('BOL','NP','REN')