CREATE VIEW USUARIOS_MEU_PORTAL_ROMMANEL AS
SELECT R_E_C_N_O_ AS REC,LTRIM(RTRIM(A1_COD)) AS CODIGO,LTRIM(RTRIM(A1_CGC)) AS CGC,
LTRIM(RTRIM(A1_NOME)) AS NOME,LTRIM(RTRIM(A1_EMAIL)) AS EMAIL,CAST(A1_DTNASC AS DATE) AS NASCIMENTO , LTRIM(RTRIM(A1_ZSENPOR)) AS SENHA
FROM SA1010 (NOLOCK) WHERE D_E_L_E_T_ = '' AND A1_ZSENPOR <> ''