	CREATE VIEW VENDAS_MEU_PORTAL_ROMMANEL AS 
	SELECT D2.R_E_C_N_O_ AS RECD2,A1.R_E_C_N_O_ AS RECA1,D2_FILIAL AS EMPRESA,D2_DOC AS DOCUMENTO,RTRIM(D2_SERIE) AS SERIE,RTRIM(D2_COD) AS PRODUTO,RTRIM(B1_DESC) AS DESCRICAO,D2_ITEM AS ITEM,D2_QUANT AS QUANTIDADE,D2_PRCVEN AS PRECO,D2_TOTAL AS TOTAL 
	FROM SD2010 (NOLOCK) D2 
	 INNER JOIN SB1010 (NOLOCK) B1 ON B1_COD = D2_COD 
	 INNER JOIN SA1010 (NOLOCK) A1 ON A1_COD = D2_CLIENTE AND A1_LOJA = D2_LOJA
	WHERE B1.D_E_L_E_T_ = '' AND D2.D_E_L_E_T_ = '' AND A1.D_E_L_E_T_ = ''